FROM gerritcodereview/gerrit:2.16.28

ADD gerrit.war /var/gerrit/bin/gerrit.war
ADD javamelody.jar /var/gerrit/plugins/javamelody.jar
ADD javamelody-deps_deploy.jar /var/gerrit/lib/javamelody-deps_deploy.jar
