global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'primary1-javamelody'
    scheme: http
    metrics_path: '/monitoring'
    params:
      format: ['prometheus']
    bearer_token: a5a737a4-3bef-4996-a5eb-7d14acf31ea8
    scrape_interval: 1s
    static_configs:
      - targets: ['primary1:8080']

  - job_name: 'primary1-metrics'
    scheme: http
    metrics_path: '/plugins/metrics-reporter-prometheus/metrics'
    params:
      format: ['prometheus']
    bearer_token: a5a737a4-3bef-4996-a5eb-7d14acf31ea8
    scrape_interval: 1s
    static_configs:
      - targets: ['primary1:8080']

  - job_name: 'primary2-javamelody'
    scheme: http
    metrics_path: '/monitoring'
    params:
      format: ['prometheus']
    bearer_token: a5a737a4-3bef-4996-a5eb-7d14acf31ea8
    scrape_interval: 1s
    static_configs:
      - targets: ['primary2:8080']

  - job_name: 'primary2-metrics'
    scheme: http
    metrics_path: '/plugins/metrics-reporter-prometheus/metrics'
    params:
      format: ['prometheus']
    bearer_token: a5a737a4-3bef-4996-a5eb-7d14acf31ea8
    scrape_interval: 1s
    static_configs:
      - targets: ['primary2:8080']