{
 "title": "Gerrit multi-site",
 "description": "Metrics dashboard for Gerrit multi-site",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Application", "label": "Application", "query": { "query": "javamelody_system_load_avg" } },
   { "name": "Window", "label": "Aggregation window", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Review-uk replication",
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(plugins_multi_site_multi_site_subscriber_subscriber_replication_status_sec_behind{instance=\"review-uk.gerrit-test.uk:8080\"}[1m])/60"
    }
   ]
  },
  {
   "title": "Review-kr replication",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(plugins_multi_site_multi_site_subscriber_subscriber_replication_status_sec_behind{instance=\"review-kr.gerrit-test.uk:8080\"}[1m])/60"
    }
   ]
  },
  {
   "title": "SSH Conn Review-uk",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(sshd_sessions_connected{instance=\"review-uk.gerrit-test.uk:8080\"}[$Window])"
    }
   ]
  },
  {
   "title": "SSH Conn Review-kr",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(sshd_sessions_connected{instance=\"review-kr.gerrit-test.uk:8080\"}[$Window])"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Offline Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publisher failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_multi_site_multi_site_broker_broker_message_publisher_failure_counter_total_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_network_requestmetrics_errors_total{request!~\".*error=NONE\"}[$Window])",
     "legendFormat": "{{instance}}/{{request}}"
    }
   ]
  },
  {
   "title": "Publisher Successes",
   "type": "graph",
   "description": "Number of published messages to the Kafka Broker, by node",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_multi_site_multi_site_broker_broker_message_publisher_counter_broker_msg_publisher_counter_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Subscriber message consumer count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "#messages" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_multi_site_multi_site_subscriber_subscriber_message_consumer_counter_total_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer Poll Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(plugins_events_kafka_kafka_subscriber_subscriber_message_consumer_poll_failure_counter_total_total[$Window]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages per topic",
   "type": "graph",
   "description": "Number of published messages to the Kafka Broker, by node",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_messagesinpersec_count[$Window])",
     "legendFormat": "{{instance}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Messages per broker",
   "type": "graph",
   "description": "Number of published messages to the Kafka Broker, by node",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_total_messagesinpersec_count{node=\"gcloud\"}[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Live Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "% Cpu Load",
   "type": "graph",
   "description": "system cpu load",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_system_cpu_load_pct[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "JGit Cache",
   "type": "graph",
   "description": "used memory for JGit cache in bytes",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(jgit_block_cache_cache_used[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HTTP Healthcheck",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(http_server_rest_api_error_count_healthcheck_com_googlesource_gerrit_plugins_healthcheck_api_HealthCheckStatusEndpoint_500__none_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSH Authentication Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(sshd_sessions_authentication_failures_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "used memory in bytes",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_memory_used_bytes[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Split Brain",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(multi_site_validation_git_update_split_brain_prevented_total_total[$Window])",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "HTTP 500",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(http_server_error_count_500_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Review-uk Max Replication Latency",
   "type": "graph",
   "description": "review-uk max replication latency by destination",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max({__name__=~'plugins_replication_replication_latency_.+',instance=~\"review-uk.+\",quantile=\"0.999\"}) by (__name__)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{__name__}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Review-kr Max Replication Latency",
   "type": "graph",
   "description": "review-kr max replication latency by destination",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max({__name__=~'plugins_replication_replication_latency_.+',instance=~\"review-kr.+\",quantile=\"0.999\"}) by (__name__)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{__name__}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "graph",
   "description": "Overall lag of the repositories version compared to the global ref-db version",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(plugins_multi_site_multi_site_subscriber_subscriber_replication_status_sec_behind[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Query Changes Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_over_time(plugins_healthcheck_querychanges_latest_latency[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Projects List Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_over_time(plugins_healthcheck_projectslist_latest_latency[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JGit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_over_time(plugins_healthcheck_jgit_latest_latency[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Auth Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_over_time(plugins_healthcheck_auth_latest_latency[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Changes Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_healthcheck_querychanges_failure_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Project List Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_healthcheck_projectslist_failure_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JGit Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_healthcheck_jgit_failure_total[$Window])",
     "legendFormat": "{{instance}} JGit Failures"
    }
   ]
  },
  {
   "title": "Auth Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(plugins_healthcheck_auth_failure_total[$Window])",
     "legendFormat": "{{instance}} JGit Failures"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "System Load",
   "type": "graph",
   "description": "system load average",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_system_load_avg[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "description": "gc time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(javamelody_memory_gc_millis[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "description": "active thread count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_threads_active_count[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unix File Descriptors Open Count",
   "type": "graph",
   "description": "unix open file descriptors count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_system_unix_file_descriptors_open_count[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "HTTP requests mean time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(javamelody_http_duration_millis[$Window])/delta(javamelody_http_hits_count[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP hits per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(javamelody_http_hits_count[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "% of HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(javamelody_http_errors_count[$Window])/delta(javamelody_http_hits_count[$Window])*100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Git", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Git upload pack - count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_total_total[$Window])",
     "legendFormat": "{{instance}} Tot git upload pack"
    }
   ]
  },
  {
   "title": "Git clone and fetch count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_CLONE_total[$Window])",
     "legendFormat": "{{instance}} Tot Clone"
    },
    {
     "expr": "increase(git_upload_pack_request_count_FETCH_total[$Window])",
     "legendFormat": "{{instance}} Tot Fetch"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Scheduled Tasks Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(queue_index_batch_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} Index"
    },
    {
     "expr": "delta(queue_receive_commits_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} Receive Commits"
    },
    {
     "expr": "delta(queue_work_queue_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} Tasks"
    },
    {
     "expr": "delta(queue_ssh_command_start_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} SSH Command start"
    }
   ]
  },
  {
   "title": "Email tasks in queue",
   "type": "graph",
   "description": "Number of email tasks in the queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "queue_send_email_total_scheduled_tasks_count-queue_send_email_total_completed_tasks_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JGit Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Pack files cached",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(jgit_block_cache_open_files[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jgit_block_cache_cache_used", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}