version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    hostname: prometheus
    domainname: gerrit-test.uk
    networks:
      gerrit-test.uk:
    volumes:
      - ./prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    user: root
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    hostname: grafana
    domainname: gerrit-test.uk
    volumes:
      - ./grafana/etc/provisioning:/etc/grafana/provisioning
      - ./grafana/etc/dashboards:/etc/grafana/dashboards
      - ./grafana-data:/var/lib/grafana
    networks:
      gerrit-test.uk:
    ports:
      - "3000:3000"

networks:
  gerrit-test.uk:
    external: true
    name: gerrit-test.uk
